import { Tyson } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import TysonCard from "../components/tyson";
import { trpc } from "../utils/trpc";
import { Spinner, Button } from "@chakra-ui/react";

const Home: NextPage = () => {
  const {
    data: pair,
    refetch,
    isLoading,
  } = trpc.useQuery(["tyson.pair"], {
    refetchInterval: false,
    refetchOnReconnect: false,
    refetchOnWindowFocus: false,
    refetchOnMount: false,
  });

  const voteMutation = trpc.useMutation(["tyson.vote"]);

  const fetchingNext = voteMutation.isLoading || isLoading;

  const voteForTyson = async (votedFor: Tyson) => {
    if (!pair) {
      return;
    }

    if (votedFor.id === pair.firstTyson.id) {
      voteMutation.mutate({
        votedFor: pair.firstTyson.id,
        votedAgainst: pair.secondTyson.id,
      });
    } else {
      voteMutation.mutate({
        votedFor: pair.secondTyson.id,
        votedAgainst: pair.firstTyson.id,
      });
    }

    refetch();
  };

  return (
    <div className="h-screen w-screen flex flex-col justify-between items-center">
      <Head>
        <title>Cutest Tyson</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center text-3xl mt-4 select-none">
        Which
        <span className="text-green-600"> Tyson</span> is cuter?
      </h1>

      {pair && (
        <div className="flex flex-col sm:flex-row justify-evenly items-center m-2 mt-6">
          <>
            <TysonCard
              tyson={pair.firstTyson}
              vote={() => voteForTyson(pair.firstTyson)}
              disabled={fetchingNext}
              key={pair.firstTyson.id}
            />
            <span className="p-8 text-xl italic select-none">or</span>
            <TysonCard
              tyson={pair.secondTyson}
              vote={() => voteForTyson(pair.secondTyson)}
              disabled={fetchingNext}
              key={pair.secondTyson.id}
            />
          </>
        </div>
      )}
      {!pair && (
        <Spinner
          color="green.500"
          size="xl"
          thickness="4px"
          emptyColor="gray.200"
        />
      )}

      <div className="flex justify-center my-4">
        <Link href="results">
          <a>
            <Button colorScheme="green">Results</Button>
          </a>
        </Link>
      </div>
    </div>
  );
};

export default Home;
